---
title: ""
author: "Chang-Yu Chang"
date: "`r Sys.Date()`" 
output: 
    bookdown::pdf_document2:
      toc: false
      number_sections: no
fontsize: 12pt
urlcolor: blue
linkcolor: red
header-includes: 
- \usepackage{float}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  cache = FALSE, 
  echo = FALSE,
	fig.align = "center",
  fig.pos = "H",
	fig.height = 4,
	fig.width = 6)
library(tidyverse)
library(data.table)
library(invnet)
root <- rprojroot::is_r_package # Package root
```


Invasion network - random assembly

`r date = "20191213"; date`
`r n_plate = 2`

# PCR with master mix in 96-well plate

Items                | Usage                             | Amount
---------------------|-----------------------------------|------------
PCR plates           | duplicate PCR                     | `r n_plate * 2`
50 mL faclon tube    | PCR master mix                    | 1
20uL tip box         | dispense                          | `r n_plate * 2 + 1`
200uL tip box        | dispense                          | 1

Table: Materials.

```{r}
n_plate = 2
# Reagents required per well
data.frame(
  Reagent = c("ddH20", "5X HF buffer", "dNTPs (10mM)", "Phusion"),
  WellVolume = c(23.5, 10, 1, 0.5),
  stringsAsFactors = F
) %>%
  mutate(TotalVolume = WellVolume * n_plate * 108 * 2) %>%
  janitor::adorn_totals() %>% 
  knitr::kable(format = "pandoc", caption = "CASEU PCR master mix.")
```


```{r}
# Reagents used with master mix
data.frame(
  Reagent = c("PCR master mix", "27F primer (3uM)", "1492R primer (3uM)", "teamplate DNA polymerase"),
  WellVolume = c(35, 5, 5, 5), 
  stringsAsFactors = F
)  %>%
  mutate(TotalVolume = WellVolume * n_plate * 108 * 2) %>% # Duplicate PCR
#  mutate(ReservoirWellVolume = TotalVolume / 12) %>%
#  janitor::adorn_totals() %>%  # Add total volume for each well and total reagent used 
  knitr::kable(format = "pandoc", caption = "CASEU PCR reagents with master mix.")
```


- Label `r n_plate * 2` PCR plates with naming convention like **T0 C P2 PCR** and **T3 C P2 PCR**.
- Make **`r total_primer_volume = n_plate * 5 * 108 * 2; total_primer_volume` uL** of 3uM of each primer (`r total_primer_volume * 0.03` uL 100 uM stock + `r total_primer_volume * 0.97` uL ddH2O).
- Premix the PCR reagents (total `r n_plate * 35 * 108 * 2 / 1000` mL) in a 50 mL falcon tube. 
- Use mP200 set at **35 uL** to dispense 35 uL of PCR master mix into each well of `r n_plate * 2` PCR plates. This premix can stay at room temperature.
- Right before starting the PCR reaction, use mP20 set at **5 uL** to add primers.
- Use mP20 set at **5 uL** to add DNA. Cover the PCR plates with clear PCR films. 
- Use the program “CASEU” in “16S” folder. See the table below for PCR cycle.
- Store PCR plates in -20C freezer.


\newpage

```{r}
# Reagents required per well
data.frame(
  Reagent = c("ddH2O", "5X HF buffer", "dNTPs (10mM)", "27F primer (3uM)", "1492R primer (3uM)", "Phusion polymerase", "template DNA"),
  WellVolume = c(23.5, 10, 1, 5, 5, 0.5, 5), 
  stringsAsFactors = F
) %>%
  janitor::adorn_totals() %>% 
  knitr::kable(format = "pandoc", caption = "CASEU PCR reagents.")

```



Step                     |  Temperature | Duration
-------------------------|--------------|-----------
Initial denaturation     | 98 C         | 30 seconds
Amplification (30 cycles)| 98 C         | 30 seconds
\space                   | 50 C         | 30 seconds
\space                   | 72 C         | 90 seconds
Final extension          | 72 C         | 10 minutes
Storage                  | 4 C          | Forever

Table: CASEU PCR cycle. 


```{r pellet-plate, fig.width=8, fig.height=5, fig.cap="C P2 plate layout."}
load(root$find_file("output/protocol/tab_fig/protocol_20191205_random_network_T2-plate_layout.Rdata"))
plates_DNA_list$DNA_C_P2
```



```{r}
# # Duplicate PCR amplification with master mix 
# 
# Input: 5 uL DNA in PCR plate pilot3_clean_DNA (Fig \@ref(fig:PCR))
# Output: 50 uL PCR DNA in each of duplicate PCR plates pilot3_PCR (Fig \@ref(fig:PCR))
# 
# 1. Thaw pilot3_clean_DNA on ice, mix to resuspend, and store on ice.
# 2. Thaw and spin down pilot3_clean_DNA plate.
# 3. Premix the PCR reagent in two master mix tube and then aliquot to PCR plates. Note: The PCR will be done in duplicate.
#     * Only pre-mix enzyme, dNTP and primers right before PCR reactions. Two master mix tubes are prepared right before running PCR.
# 4. Add control DNA (5ng/uL) to control wells prior to sealing the PCR plates and running the PCR. Add transparent PCR film (not foil) to the plates when finished, centrifuge briefly, and PCR immediately.
# 5. To run the PCR, use the program “CASEU” in “16S” folder. See the table below for PCR reagent and cycle.
# 6. Store PCR plates pilot3_PCR at -20C.
```






