---
title: "Determine the pairwise interactions in the simulated communities"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    number_sections: no
    toc: yes
linkcolor: red
fontsize: 12pt
urlcolor: blue
---

```{r setup, include = FALSE}
# Knitr options
knitr::opts_chunk$set(
  cache = FALSE, 
  echo = FALSE,
	fig.align = "center",
	fig.height = 3,
	fig.width = 3)

# Packages
library(tidyverse)
library(data.table)
library(invnet)
#library(reticulate) # Python interface
#reticulate::use_python('~/anaconda3/bin/python3.7m') # Use this python version

# Local directory and functions
root <- rprojroot::is_r_package # Package root
source(root$find_file("misc/utils.R"))
source(root$find_file("misc/network_functions.R"))
write_all_csv <- TRUE
write_all_pdf <- TRUE
```

```{python include = F}
# Python version
import sys
print(sys.version)
```

# Read the simulation result

```{r}
source("script/04A-self_assembly-01-read_simulation_data.R")
```

```{r}
if (TRUE) {
  fwrite(df_self_assembly, root$find_file("output/report/data/temp/df_self_assembly.txt"))
  fwrite(df_mono, root$find_file("output/report/data/temp/df_mono.txt"))
  fwrite(df_grower, root$find_file("output/report/data/temp/df_grower.txt"))
  fwrite(df_pair, root$find_file("output/report/data/temp/df_pair.txt"))
}
```

# Plot the community properties

Richness

```{r}
p_self_assembly[[1]]
```

Relative abundances, 4 self-assembled communities for example

```{r}
p_self_assembly[[3]]
```

Relative abundances of 96 self-assembled communities at the 10th transfer

```{r}
p_self_assembly[[4]]
pdf(root$find_file("output/report/figure/04A-self_assembly-self_assembled_communities.pdf")); p_self_assembly[[4]]; invisible(dev.off())
```

Check for alternative states 

```{r}
p_temp <- df_self_assembly %>%
  filter(Transfer == 6, Type == "consumer") %>%
  group_by(Transfer, Community, Type) %>%
  arrange(desc(Abundance)) %>%
  mutate(MostAbundanceID = ID[1]) %>%
  mutate(RelativeAbundace = Abundance / sum(Abundance)) %>%
  ggplot() +
  geom_bar(aes(x = Community, y = RelativeAbundace, fill = ID),
           color = "black", lwd = .3, stat = "identity") +
  facet_grid(Type ~ MostAbundanceID, scale = "free") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  guides(fill = F, color = F)

p_temp
#pdf(root$find_file("output/figure/self_assembly-typeIII.pdf"), width = 10, height = 5); p_temp; invisible(dev.off())
```


Monoculture growth

```{r}
p_mono[[2]]
#pdf(root$find_file("output/report/figure/04A-self_assembly-monoculture_growth.pdf")); p_mono[[2]]; invisible(dev.off())

# List of grower identified by monoculture
df_mono %>%
  filter(Type == "consumer", Transfer == 10) %>%
  pull(ID) %>% as.character() # %>% paste0(collapse = ", ")
```



# Determine the pairwise interactions

```{r message = F}
source("script/04A-self_assembly-02-determine_pairwise_interaction.R")
```

```{r}
if (write_all_csv) fwrite(df_pair_interaction, root$find_file("output/report/data/temp/df_pair_interaction.txt"))
```


With undefined interactions

```{r fig.width=5, fig.height=3}
# Plot the fraction of pairwise interactions
## Interaction frequency
p_interaction_frequency <- df_pair_interaction %>%
  # Filter out undefined 
  filter(InteractionType != "undefined") %>% 
  # Count each type of pairwise competition
  group_by(Assembly, Community, InteractionType) %>%
  summarize(Count = n()) %>%
  # Undefined interactions because of the pairs of non-growers
  replace_na(list(InteractionType = "undefined")) %>%
  # Frequency of each interaction Type
  group_by(Assembly, Community) %>%
  mutate(Frequency = Count / sum(Count)) %>%
  ggplot() +
  geom_bar(aes(x = Community, y = Frequency, fill = InteractionType), stat = "identity", color = "black") +
  #  scale_y_continuous(limits = c(0, 1)) +
  facet_wrap(Assembly~.) +
  theme_bw() +
  theme(legend.position = "top")
p_interaction_frequency

```

With undefined interactions

```{r fig.width=5, fig.height=3}
# Plot the fraction of pairwise interactions
## Interaction frequency
p_interaction_frequency <- df_pair_interaction %>%
  # Filter out undefined 
#  filter(InteractionType != "undefined") %>% 
  # Count each type of pairwise competition
  group_by(Assembly, Community, InteractionType) %>%
  summarize(Count = n()) %>%
  # Undefined interactions because of the pairs of non-growers
  replace_na(list(InteractionType = "undefined")) %>%
  # Frequency of each interaction Type
  group_by(Assembly, Community) %>%
  mutate(Frequency = Count / sum(Count)) %>%
  ggplot() +
  geom_bar(aes(x = Community, y = Frequency, fill = InteractionType), stat = "identity", color = "black") +
  #  scale_y_continuous(limits = c(0, 1)) +
  facet_wrap(Assembly~.) +
  theme_bw() +
  theme(legend.position = "top")
p_interaction_frequency

```


