---
title: "Detect the network structures in simulated self-assembled communities"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    number_sections: no
    toc: yes
linkcolor: red
fontsize: 12pt
urlcolor: blue
---

```{r setup, include = FALSE}
# Knitr options
knitr::opts_chunk$set(
  cache = FALSE, 
  echo = FALSE,
	fig.align = "center",
	fig.height = 3,
	fig.width = 3)

# Packages
library(tidyverse)
library(data.table)
library(cowplot)
library(invnet) # Self-use package
library(igraph)
library(tidygraph)

# Local directory and functions
root <- rprojroot::is_r_package # Package root
source(root$find_file("misc/utils.R"))
source(root$find_file("misc/network_functions.R"))
write_all_csv <- TRUE
write_all_pdf <- TRUE
```



# Make and plot networks

```{r warning = F}
source("script/04B-network_analysis-01-make_network.R")
```



```{r fig.width = 4, fig.height = 4}
p_net_matrix_list
```


```{r fig.width = 4, fig.height = 4}
p_net_matrix <- plot_grid(plotlist = p_net_matrix_list[-4], nrow = 2, align = "h", axis = "bt")
p_net_matrix
pdf(root$find_file("output/report/figure/04C-network_analysis-network_matrix.pdf"), width = 8, height = 8); p_net_matrix; invisible(dev.off())
```




# Isolate ranks

```{r}
# Read data
df_grower <- fread(root$find_file("output/report/data/temp/df_grower.txt"))

# Growth rank for growers
df_grower_rank <- df_grower %>% 
  arrange(desc(Abundance)) %>%
  mutate(OD = Abundance, GrowthRank = 1:nrow(.)) %>%
  select(ID, OD, GrowthRank)

# Isolate competitive hierarchy
df_isolates_rank <- lapply(net_list, tournament_rank) %>% rbindlist()
```

Growth ranks vs. competitive ranks 

```{r}
df_isolates_rank %>%
  filter(Community != "W14a") %>%
  select(Community, ID, Rank) %>%
  mutate(ID = as.numeric(as.character(ID))) %>%
  left_join(df_grower_rank, by = "ID") %>%
  ggplot(aes(x = GrowthRank, y = Rank)) +
  geom_point() +
  facet_wrap(Community~.) +
  theme_bw()
```



# Motif detection

```{r}
source("script/04C-network_analysis-02-motif.R")
```


```{r fig.width = 4, fig.height = 3}
p_network_motif <- 
  net_list %>%
  lapply(function(net) {
      data.frame(Motif = paste0("motif", 1:7),
        Count = motif_detect(net))
  }) %>%
  rbindlist(idcol = "Community") %>%
  filter(Community != "W14a") %>% 
  ggplot(aes(x = Motif, y = Count, group = Community)) +
  geom_point() + geom_line() +
  facet_wrap(Community ~ ., ncol = 1, scale = "free_y") +
  theme_bw()
```


```{r fig.width=6, fig.height=10}
temp_p <- plot_grid(p_motif_example, p_network_motif, ncol = 1, rel_heights = c(0.2, 1.5))
temp_p
pdf(root$find_file("output/report/figure/04C-motif.pdf"), width = 12, height = 20); temp_p; invisible(dev.off())
```

















