---
title: "Experiment on competitive networks of random isolates and self-assembled isolates"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
fontsize: 12pt
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = FALSE)
library(tidyverse)
library(data.table)
library(cowplot)
#source("../../misc/utils.R")
#write_all_csv <- T
#write_all_pdf <- T

# 
communities <- fread("../../data/temp/communities.csv")
communities_name <- communities$Community
communities_size <- communities$CommunitySize
#isolates_ID_match <- fread("../../data/temp/isolates_ID_match.csv")
isolates <- fread("../../data/output/isolates.csv")
#jean_isolates_RDP <- fread("../../data/temp/jean_isolates_RDP.csv")
```



# Pick random isolates for assembly

```{r message = F, warning= F}
source("script/05A-random_network_experiment-01-pick_isolates.R")
```


4 communities, 8 isolates each. 16 isolates are from random isolate from Jean's collection, and 16 isolates are from self-assembled communities


```{r}
if (write_all_csv) fwrite(isolates_assembly, file = "../../data/temp/random_network_isolates.csv"))
```




























