---
title: "Experiment on competitive networks of random isolates and self-assembled isolates"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
linkcolor: red
fontsize: 12pt
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  cache = TRUE, 
  echo = FALSE,
	fig.align = "center",
	fig.height = 4,
	fig.width = 6)
library(tidyverse)
library(data.table)
library(invnet)
library(cowplot)
root <- rprojroot::is_r_package # Package root
source(root$find_file("misc/utils.R"))
write_all_csv <- T
write_all_pdf <- T

# 
communities <- fread(root$find_file("data/temp/communities.csv"))
communities_name <- communities$Community
communities_size <- communities$CommunitySize
isolates_ID_match <- fread(root$find_file("data/temp/isolates_ID_match.csv"))
isolates <- fread(root$find_file("data/output/isolates.csv"))
jean_isolates_RDP <- fread(root$find_file("data/temp/jean_isolates_RDP.csv"))
```

# Map plate layout

```{r warning = F}
source("script/05B-random_network_OD-01-map_plate_layout.R")
```

```{r}
pdf(root$find_file("output/report/figure/05B-random_network_OD-plate_layout.pdf"), width = 15, height = 12);
plot_grid(plotlist = p_random_network_plates_list, ncol = 3, nrow = 3, , labels = names(p_random_network_plates_list)); invisible(dev.off())
```


```{r}
if (write_all_csv) fwrite(random_assembly_plates, file = root$find_file("data/temp/random_assembly_plates.csv"))
save(p_random_network_plates_list, file = root$find_file("data/temp/random_network_plate_layout.RData"))
```

# Read OD data

```{r warning = F}
source("script/05B-random_network_OD-02-read_OD_data.R")
OD
```

```{r message = F, warning = F, fig.width=5, fig.height = 4}
# Plot the OD 
p_random_network_OD <- rep(list(NA), 4)
for (i in 1:4) {
  p_random_network_OD[[i]] <- 
    OD %>% 
    filter(Community == random_community_names[i], Wavelength == 620) %>% 
    mutate(Transfer = as.numeric(gsub("T", "", Transfer))) %>% 
    #  replace_na(replace = list(Isolate1Freq = "mono", Isolate2Freq = "mono")) %>%
    group_by(Transfer, Community, Isolate1, Isolate2, Isolate1Freq) %>% 
    summarize(AbsMean = mean(Abs), AbsSd = sd(Abs)) %>% 
    ggplot(aes(x = Transfer, y = AbsMean, color = Isolate1Freq)) +
    geom_point() + geom_line() +
    geom_segment(aes(x = Transfer, xend = Transfer, y = AbsMean + AbsSd, yend = AbsMean - AbsSd)) +
    scale_x_continuous(breaks = 0:10, limits = c(0, 4)) + 
    facet_grid(Isolate1 ~ Isolate2) +
    theme_bw() +
    ggtitle(random_community_names[i])
}
p_random_network_OD
```

```{r}
OD %>% 
  filter(Community == "EP", Wavelength == 620) %>% 
  mutate(Transfer = as.numeric(gsub("T", "", Transfer))) %>% 
  #  replace_na(replace = list(Isolate1Freq = "mono", Isolate2Freq = "mono")) %>%
  group_by(Transfer, Community, Isolate1, Isolate2, Isolate1Freq) %>%
  summarize(AbsMean = mean(Abs), AbsSd = sd(Abs)) %>% 
  ggplot(aes(x = Transfer, y = AbsMean, color = Isolate1Freq)) +
  geom_point() + geom_line() +
  scale_x_continuous(breaks = 0:10, limits = c(0, 3)) + 
  facet_grid(Isolate1 ~ Isolate2) +
  theme_bw()
```



Check contamination

```{r}
OD %>% 
  filter(Wavelength == 620, Community != "blank") %>% 
  filter(Isolate1 == Isolate2) %>%
  group_by(Community, Isolate1) %>% 
  ggplot() +
  geom_point(aes(x = Isolate1, y = Abs, color = Isolate1Freq)) +
  facet_grid(Transfer ~ Community , scales = "free_y") +
  theme_bw()
  
```







