---
title: "Determine interaction types in random network"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
linkcolor: red
fontsize: 12pt
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  cache = TRUE, 
  echo = FALSE,
	fig.align = "center",
	fig.height = 4,
	fig.width = 6)
library(tidyverse)
library(data.table)
library(invnet)
library(cowplot)
root <- rprojroot::is_r_package # Package root
source(root$find_file("misc/utils.R"))
source(root$find_file("misc/network_functions.R"))
write_all_csv <- T
write_all_pdf <- T

# 
communities <- fread(root$find_file("data/temp/communities.csv"))
communities_name <- communities$Community
communities_size <- communities$CommunitySize
isolates_ID_match <- fread(root$find_file("data/temp/isolates_ID_match.csv"))
isolates <- fread(root$find_file("data/output/isolates.csv"))
jean_isolates_RDP <- fread(root$find_file("data/temp/jean_isolates_RDP.csv"))
isolates_assembly <- fread(root$find_file("data/temp/isolates_assembly.csv"))
```

This Rmd reads the processed CASEU output, adds the isolate properties to the pairs, determines the pairwise interaction types, then determine the network properties.  

# Determine interaction types

```{r}
source("script/05D-random_network_interaction-01-determine_interactions.R")
```

```{r eval = F}
if (write_all_csv) {
  fwrite(random_network_pairs, file = root$find_file("data/temp/random_network_pairs.csv"))
  fwrite(random_network_pairs_frequency, file = root$find_file("data/temp/random_network_pairs_frequency.csv"))
}
```


```{r}
random_network_pairs <- fread(root$find("data/temp/random_network_pairs.csv"))
random_network_pairs_frequency <- fread(root$find("data/temp/random_network_pairs_frequency.csv"))
random_network_pairs
random_network_pairs_frequency
```


```{r}
random_network_pairs %>%
  group_by(Community, InteractionType) %>% 
  summarize(Count = n())
```



# Determine network properties


```{r message = F, eval = F}
source("script/05D-random_network_interaction-02-network_properties.R")
```

```{r}
if (write_all_csv) fwrite(random_network_communities_hierarchy, root$find_file("data/temp/random_network_communities_hierarchy.csv"))
```


Matrix

```{r}
pdf(root$find_file("output/figure/random_network_communities_pairwise_matrix.pdf"), width = 13, height = 10); for (i in 1:length(p_random_network_matrix_list)) print(p_random_network_matrix_list[[i]]); invisible(dev.off())
p_random_network_matrix_list
```

Network motif

```{r}
# Plot the motif examples ----
# Motif list
motif_list <- rep(list(NA), 7)
temp_id <- c(11, 7, 8, 12, 13, 14, 15)
g <- igraph::graph.isocreate(size = 3, 1)
layout <- create_layout(g, layout = 'circle')


for (i in 1:7) {
  g <- igraph::graph.isocreate(size = 3, temp_id[i])
  E(g)$InteractionType <- ifelse(which_mutual(g), "coexistence", "exclusion")
  g <- tidygraph::as_tbl_graph(g) %>%
    mutate(x = layout$x, y = layout$y, graph = paste0("motif", i))
  motif_list[[i]] <- g
}

# Plot
set_graph_style(plot_margin = margin(1,1,1,1))
# Color setting
interaction_type <- c("exclusion", "coexistence", "lose", "bistability", "neutrality", "self", "undefined")
myColor = c("#DB7469", "#557BAA", "#73C966", "#EECF6D", "#8650C4", "black", "grey80")
names(myColor) <- interaction_type
node_size <- 5

p_motif_example <-
  tidygraph::bind_graphs(motif_list[[1]], motif_list[[2]], motif_list[[3]], motif_list[[4]], motif_list[[5]], motif_list[[6]], motif_list[[7]]) %>%
  ggraph(layout = "nicely") +
  geom_edge_link(aes(color = InteractionType), width = 1,
                 arrow = arrow(length = unit(node_size, "mm"), type = "open", angle = 20),
                 start_cap = circle(node_size, "mm"),
                 end_cap = circle(node_size, "mm")) +
  geom_node_point(size = node_size + 2, color = "black") +
  scale_edge_color_manual(values = myColor) +
  facet_nodes(~graph, nrow = 1) +
  theme_graph() +
  theme(
    legend.position = "none",
    legend.direction = "none",
    legend.title = element_blank(),
    strip.text = element_blank()
  )

# Plot observations and 5% and 95% percentiles ----
p_motif_rand <-
  ggplot() +
  # 5% and 95% percentiles in randomized networks
  geom_point(data = random_networks_motif_rand_percentile, aes(x = Motif, y = CountMotif, group = Motif), col = "black") +
  geom_segment(data = spread(random_networks_motif_rand_percentile, Percentile, CountMotif),
               aes(x = Motif, xend = Motif, y = p5, yend = p95), col = "black") +
  # Observations
  geom_point(data = random_networks_motif, aes(x = Motif, y = CountMotif), col = "red") +
  facet_wrap(Community ~., scale = "free_y") +
  theme_bw() +
  ggtitle("Motif counts in the invasion networks") +
  labs(x = "motif", y = "Count")


# Plot histogram in motif count distribution ----
p_motif_rand_histo <-
  random_networks_motif_rand %>%
  ggplot() +
  geom_histogram(aes(CountMotif), fill = NA, col = 1) +
  geom_vline(data = random_networks_motif, aes(xintercept = CountMotif), col = "red") +
  geom_rect(data = spread(random_networks_motif_rand_percentile, Percentile, CountMotif),
    aes(xmin = p5, xmax = p95), ymin = -Inf, ymax = Inf, fill = "black", alpha = 0.3) +
  facet_grid(Community ~ Motif, scale = "free") +
  coord_flip() +
  theme_bw() +
  theme(strip.text.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 90)) +
  labs(x = "motif counts", y = "counts in randomization")

p_motif_rand_histo <- plot_grid(p_motif_example, p_motif_rand_histo,
  ncol = 1, rel_heights = c(0.5, 1.5), align = "v", axis = "lr")

```

```{r fig.width=5, fig.height=5}
p_motif_rand
pdf(root$find_file("output/figure/random_network_motif_randomization.pdf"), width = 5, height = 5); p_motif_rand; invisible(dev.off())
```


```{r}
pdf(root$find_file("output/figure/random_network_motif_histogram.pdf"), width = 15, height = 10); p_motif_rand_histo; invisible(dev.off())
p_motif_rand_histo
```




```{r}
communities_hierarchy <- fread(root$find_file("data/temp/communities_hierarchy.csv"))
random_network_communities_hierarchy <- fread(root$find_file("data/temp/random_network_communities_hierarchy.csv"))

p_communities_hierarchy <- 
  bind_rows(communities_hierarchy, random_network_communities_hierarchy) %>%
  ggplot() +
  geom_bar(aes(x = Community, y = HierarchyScore), stat = "identity", col = 1) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "community", y = "hierarchy score")

p_communities_hierarchy
pdf(root$find_file("output/figure/communities_hierarchy.pdf"), width = 5, height = 3); p_communities_hierarchy; invisible(dev.off())

    
```





