---
title: "Isolate data"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = FALSE)
library(tidyverse)
library(data.table)
```

68 isolates used in the competitve assay. The csv saves `ExpID` for isolation, `ID` for Sanger sequencing, `Community` and `Isolate` for ID used in competitive assay.

```{r}
# Community isolates
isolates_comm <- fread(here::here("data/raw/pairwise_competition", "isolates1.csv")) %>%
    select(ExpID, ID, Community, Isolate)

# Natural isolates
isolates_random <- fread(here::here("data/raw/pairwise_competition", "isolates_random.csv")) %>%
    select(Community = AssemblyCommunity, ExpID, Isolate = AssemblyIsolate)
ID_jean <- data.table::fread(here::here("data/raw/Sanger/", "jean_isolate_ids.csv")) %>%
 filter(!is.na(V2)) %>%
 select(V1, V2) %>%
 setNames(c("ExpID", "ID"))
isolates_random <- isolates_random %>% left_join(ID_jean)
for (i in 1:nrow(isolates_random)) {
   if (is.na(isolates_random$ID[i])) {
      isolates_random$ID[i] <- isolates_comm$ID[which(isolates_comm$ExpID == isolates_random$ExpID[i])]
   }
}

isolates_ID_match <- bind_rows(isolates_comm, isolates_random)
fwrite(isolates_ID_match, here::here("data/temp/", "isolates_ID_match.csv"))
isolates_ID_match

```

Community IDs and basic information

```{r}
communities_name <- c("C1R2", "C1R4", "C1R6", "C1R7", "C2R6", "C2R8", "C4R1", "C7R1", "C8R4", "C10R2", "C11R1", "C11R2", "C11R5")
communities_size <- c(4,5,5,7,4,4,3,4,3,3,9,12,5)
pp <- function(x) choose(x, 2)
tt <- function(x) choose(x, 3)

communities <- data.frame(
  Community = communities_name,
  CommunitySize = communities_size,
  CommunityPairSize = pp(communities_size),
  CommunitiyMotifSize = tt(communities_size)
)

fwrite(communities, here::here("data/output/communities.csv"))
communities
```
