---
title: "Competitive networks of random isolates and self-assembled"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, echo = FALSE)
library(tidyverse)
library(data.table)
library(cowplot)

# 
communities <- fread(root$find_file("data/temp/communities.csv"))
communities_name <- communities$Community
communities_size <- communities$CommunitySize
random_network_communities_name <- c("AcrAss1", "AcrAss2", "RanAss1", "RanAss2")
random_network_communities_size <- rep(7, 4) 
isolates_ID_match <- fread(root$find_file("data/temp/isolates_ID_match.csv"))
isolates <- fread(root$find_file("data/output/isolates.csv"))
jean_isolates_RDP <- fread(root$find_file("data/temp/jean_isolates_RDP.csv"))
```



# Fraction of pairwise coexistence within community  

```{r message = F}
pairs <- read_csv(root$find_file("data/output/pairs.csv"))
random_network_pairs <- read_csv(root$find_file("data/temp/random_network_pairs.csv"))
pairs_combined <- select(pairs, names(random_network_pairs)) %>%
  bind_rows(random_network_pairs)
```


```{r}
communities_pair_coext <- pairs_combined %>%
  mutate(Community = ordered(Community, levels = c(communities_name, random_network_communities_name))) %>%
  filter(InteractionType != "") %>%
  filter(InteractionType %in% c("exclusion", "coexistence")) %>%
  group_by(Community, InteractionType) %>%
  summarize(Count = n()) %>%
  spread(InteractionType, Count) %>%
  mutate(FracCoext = coexistence / (coexistence + exclusion)) %>%
  ungroup() %>%
  mutate(CommunitySize = c(communities_size, random_network_communities_size[3]))

communities_pair_coext$FracCoext[is.na(communities_pair_coext$FracCoext)] <- 0
```

Fraction of coexistence in 13 communities

```{r}
p_communities_pair_coext <- 
communities_pair_coext %>%
  ggplot() +
  geom_bar(aes(x = Community, y = FracCoext), stat = "identity", col = 1) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "community", y = "fraction of coexistence")

p_communities_pair_coext
pdf(root$find_file("output/figure/communities_fraction_coexistence.pdf"), width = 5, height = 3); p_communities_pair_coext; invisible(dev.off())
```

# Community hierarchy in communities


From Higgins2017, the competitive score $s_i$ of each strain $i$ was defined as its mean fraction $f_{ij}$ after co-culture with each of the $n-1$ competitor strains:

$$s_i=(\sum_{i\neq j}f_{ij})/(n-1)$$

The hierarchy score $h$ for an n-member network is calculated as:

$$h = \sum_{s_i>s_j}f_{ij}$$

```{r}
communities_hierarchy <- fread(root$find_file("data/temp/communities_hierarchy.csv"))

p_communities_hierarchy <- communities_hierarchy %>%
  ggplot() +
  geom_bar(aes(x = Community, y = HierarchyScore), stat = "identity", col = 1) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "community", y = "hierarchy score")

p_communities_hierarchy
pdf(root$find_file("output/figure/communities_hierarchy.pdf"), width = 5, height = 3); p_communities_hierarchy; invisible(dev.off())

    
```



# EP pair

```{r}
EP_pairs <- fread(root$find_file("data/raw/pairwise_competition/EP_pairs.csv")) %>% 
  mutate(Isolate1Freq = Isolate1Colony / (Isolate1Colony + Isolate2Colony))

p_temp <- EP_pairs %>% mutate(Time = "T3") %>% 
  bind_rows(EP_pairs %>% mutate(Time = "T0", Isolate1Freq = Isolate1InitialODFreq/100)) %>% 
  mutate(Isolate1InitialODFreq = factor(Isolate1InitialODFreq), Time = ordered(Time)) %>% 
  filter(Replicate == "a") %>% 
  select(Isolate1InitialODFreq, Time, Isolate1Freq) %>%
  group_by(Isolate1InitialODFreq) %>% 
  ggplot(aes(x = Time, y = Isolate1Freq, color = Isolate1InitialODFreq, group = Isolate1InitialODFreq)) +
  geom_point() + geom_line() +
  theme_bw() +
  theme(legend.position = "top") +
  labs(y = "E frequenency")


pdf(root$find_file("output/report/figure/05-random_network-EP_pairs.pdf")); p_temp; invisible(dev.off())
```














