---
title: "Determine interaction types in random network"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, echo = FALSE)
library(tidyverse)
library(data.table)
library(cowplot)
source(here::here("plotting_scripts/network_functions.R"))
```

This Rmd reads the processed CASEU output, adds the isolate properties to the pairs, determines the pairwise interaction types, then determine the network properties.  

# Determine interaction types

```{r}
source("script/05D-random_network_interaction-01-determine_interactions.R")
```



```{r}
random_network_pairs
random_network_pairs_frequency
```

```{r}
random_network_pairs %>%
  group_by(Community, InteractionType) %>% 
  summarize(Count = n())
```

```{r}
plot_frequency <- function(pairs_melted) {
  pairs_melted %>%
    mutate(Isolate = factor(Isolate1, 1:8), Isolate2 = factor(Isolate2, 1:8)) %>%
    mutate(Isolate1InitialODFreq = factor(Isolate1InitialODFreq)) %>%
    ggplot(aes(x = Time, y = Isolate1MeasuredFreq, color = Isolate1InitialODFreq, group = Isolate1InitialODFreq)) +
    geom_line() +
    geom_point() +
    facet_grid(Isolate1~Isolate2) +
    theme_bw() +
    theme(legend.position = "top")
} 

p1 <- random_network_pairs_melted %>%
  filter(Community == "AcrAss1") %>%
  plot_frequency() +
  ggtitle("AcrAss1")
p2 <- random_network_pairs_melted %>%
  filter(Community == "RanAss1") %>%
  plot_frequency() +
  ggtitle("RanAss1")
p3 <- random_network_pairs_melted %>%
  filter(Community == "RanAss2") %>%
  plot_frequency() +
  theme(legend.position = "none") +
  ggtitle("RanAss2") 


p <- plot_grid(p1, p2, p3, nrow = 2)
ggsave(here::here("output/report/figure/05D-random_network_interaction-frequency.png"), p, width = 12, height = 12)
```


# Determine network properties


```{r message = F, eval = F}
source("script/05D-random_network_interaction-02-network_properties.R")
```


Matrix

```{r}
p <- plot_grid(plotlist = p_random_network_matrix_list, nrow = 1)
ggsave(here::here("output/report/figure/05D-random_network_interaction-adjacent_matrix.png"), p, width = 8, height = 4)

```

Network motif

```{r}
ggsave(here::here("output/report/figure/05D-random_network_interaction-motif.png"), p_random_networks_motif_randomized, width = 8, height = 4)
```





