---
title: "README for the analyses on invasion network"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
linkcolor: red
fontsize: 12pt
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  cache = TRUE, 
  echo = TRUE,
	fig.align = "center",
	fig.height = 4,
	fig.width = 6)
library(tidyverse)
library(data.table)
library(invnet)
root <- rprojroot::is_r_package
```

# Please read this file before going through the analyses and all reports

This report describes the management logics of my analysis scripts. Every "reports" are numbered based on the analyzed subjects (e.g., isolates or pairs) and the data types (e.g., Sanger sequences or colony counts). For instance this Rmd `00-index.Rmd` is createad for explaining the logics. 

For particular **analysis subject**, there are main indexed report like `01-isolates.Rmd`, which focuses on the isolates' information. It takes the output data in folder `data/temp/`, which are in csv or Rdata form and were generated by sub-reports such as `01A-isolates_sanger_seq.Rmd`, `01B-isolates_OD_CFU.Rmd`, and `01C-isolates_chromogenic_plate.Rmd`. 

Under a paritcular analysis subject, the sub-reports are seaparated according the target **raw data types**. For example, `01A-isolates_sanger_seq.Rmd` takes the isolate 16S Sanger sequences, `01B-isolates_OD_CFU.Rmd` compares and converts isolates' OD to CFU, and `01C-isolates_chromogenic_plate.Rmd` has the information for isolates that are distingusishable on chromogenic plates.

# Workflow of analyses

The critical part is the chronology of analyses. In principle, the sub-reports are used for exploratory data anaylsis, so it's always analyzed (or script being run) before the main indexed reports take the temporary data in folder  `data/temp/` and process to publication ready figures. So the primary workflow of analyses is as follow:

1. Raw data saved in `data/raw/`.
2. Exploratory data analysis in sub-reports (e.g.,`01A-isolates_sanger_seq.Rmd`)
    - It produces temporary data in `data/temp/`
    - It also produces report-only figures in `output/report/figure/`
    - R scripts used for each EDA report in `output/report/script/` with file name initial the same as the EDA report that uses them.
3. Main indexed reports that are specific to a main subject (e.g., `01-isolates.Rmd`)
    - It also preduces publication-ready data in `output/figure`
    - It also produces publicaiton-ready figures in `output/figure/`
    - R scripts used in in each report in `output/report/script/`


Here is the nested structured of all analysis reports.

- 00-index.Rmd
- 01-isolates.Rmd
    - 01A-isolates_sanger_seq.Rmd
    - 01B-isolates_OD_CFU.Rmd
    - 01C-isolates_chromogenic_plate.Rmd
- 02-pairs.Rmd
    - 02A-CASEU_sanger_seq.Rmd
    - 02B-pairs_OD_CFU.Rmd
    - 02C-competition_phylogeny.Rmd
- 03-invasion_network.Rmd


# Exploratory Data Analysis (EDA)

There is a consistent structure that I used throughout all EDA reports.

- Goal: listed goals for this report. Usually I limit the number of goals up to 5 in an EDA.

- Install packages: installed required packages for this EDA if there are not `tidyverse`, `data.table`, or `invnet`, which is the pakcages I used most of the time.

- Analysis sections: these sections depend on the relevent anaylsis for the files so that there is no fixed name for these sections. However, there is custom that I usually have **one R script** (also its file name is numbered) for containing most codes in this section. The R script is immediately run right below the section title. These R scripts are saved in the subfolder `output/report/script/` and called by using `source()`.


For modifying the R lansdcape and the external environments (e.g., read and write files), I keep the following standards:

- R scripts read raw data in `data/raw/` and R chunks in EDA report reads the temporary data `data/temp/`.

- In EDA report, **only write output files in Rmd** rather than in the R scripts. Ideally I don't have to check the R scriptes if I have to re-run the Rmd analyses. Same rule apply to output pdf file (e.g., figures in `output/report/figure/`).

- All output csv and pdf files have prefix that compasses the EDA report names.

- Before finishing a section, I usually save the files in `data/temp/` and read them in the beginning of the next section. But this rule does not apply if the temporaray data will for sure not be read by another EDA report.















