---
title: "Farmer selection"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
  pdf_document:
    toc: yes
  bookdown::pdf_document2:
    number_sections: no
    toc: no
linkcolor: red
fontsize: 12pt
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  cache = TRUE, 
  echo = TRUE,
	fig.align = "center",
	fig.height = 4,
	fig.width = 6)
#  engine.path = '~/anaconda3/bin/python3.7m')
library(tidyverse)
library(data.table)
library(reticulate) # Python interface
reticulate::use_python('~/anaconda3/bin/python3.7')
#library(invnet)
root <- rprojroot::is_r_package
```


```{r}
# .. we will normally have one initial and one final reading, in two separate
#    files. Note that in this case (T2) it is a bit different
read.spec.data <- function(f, reader)    
{
  require(data.table)
  options(stringsAsFactors = FALSE)
  if (reader == 1) {
    x <- read.delim(f, row.names=NULL)
    x <- data.table('plate' = x$Plate,
                    'well' = x$Well,
                    'row' = match(substr(x$Well, 2, 2), LETTERS),
                    'col' = ordered(as.numeric(substr(x$Well, 3, 4))),
                    'wl' = x$Wavelength,
                    't' = round((x$Meas..Time..s.)/60, 0),
                    'abs' = x$Abs)
    x[,well := gsub(' ', '', well)]  
  }
  
  if (reader == 2) {
    
    #nread <- 1
    #aux <- readLines(f, n=nread)
    
    #while (!any(grep('avg.time', aux))) {
    #  nread <- nread+1
    #  aux <- readLines(f, n=nread)
    #}
    
    # wavelength
    wl <- grep('Wavelength: ', aux)
    wl <- as.numeric(gsub('\\D+','', aux[wl]))
    
    # plate name, usually in line 2 
    plate <- gsub('\t', '', aux[2])
    
    # .. col names 
    cn <- unlist(strsplit(aux[nread], '\t'))[-(1:2)]
    wells <- gsub('.*[(]([^.]+)[)].*', '\\1', cn)
    
    # .. read data            
    x <- read.delim(f, row.names=NULL, skip=nread, header=FALSE)
    names(x) <- c('plate', 'well', wells)
    x <- data.table(x)
    x[, t := round(`Meas. Time [s]`/60)]
    x <- x[Reading == max(Reading)]
    
    # .. update dataframe
    x[, well := substr(well, 2, 4)]
    x[, plate := plate]
    x[, abs := `Abs  `]
    #x[, row := match(substr(well, 1, 1), LETTERS)]
    #x[, col := as.numeric(substr(well, 2, 3))]
  }
  return(x)
}

```


```{r}
folder <- '~/ownCloud/Chang-Yu/Farmer_round2/'
#setwd("/Users/yoyoy/ownCloud/Chang-Yu/Farmer_round2")

f <- list.files(folder)
exp_names <- c("Farmer_T1_expt_list", "Farmer_T2_expt_list", "Farmer_T3_expt_P1_list", "Farmer_T4_expt_list", "Farmer_T5_expt_list", "Farmer_T6_expt_list", "Farmer_T7_expt_list", "Farmer_T8_expt_list")
ctrl_names <- c("Farmer_T1_ctrl_list", "Farmer_T2_screen_ctrl_30hr_list_1", "Farmer_T3_ctrl_list", "Farmer_T4_ctrl_list", "Farmer_T5_ctrl_list", "Farmer_T6_ctrl_list", "Farmer_T7_ctrl_list", "Farmer_T8_ctrl_list")

exp_result_list <- rep(list(NA), 8)
ctrl_result_list <- rep(list(NA), 8)

for (i in 1:8) {
#  exp_result_list[[i]] <- fread(paste0(folder, exp_names[i], ".txt"))
  exp_result_list[[i]][,"Plate"] <- paste0("T", i, "_expt")
  ctrl_result_list[[i]] <- fread(paste0(folder, ctrl_names[i], ".txt"))
  ctrl_result_list[[i]][,"Plate"] <- paste0("T", i, "_ctrl")
  
}

exp_plate <- rbindlist(exp_result_list)
ctrl_plate <- rbindlist(ctrl_result_list)
result <- rbind(exp_plate, ctrl_plate)

temp <- strsplit(result$Plate, "_") %>% unlist() %>%
  matrix(ncol = 2, byrow = T) %>% as.data.frame() %>%
  setNames(c("Transfer", "Treatment"))
result <- cbind(temp, result)
```
```{r}
read.spec.data(paste0(folder, "T2_screen_ctrl_22hr.txt"), reader = 2)

```



```{r}
result %>%
  filter(Wavelength == 620) %>%
  ggplot(aes(x = Well, y = Abs, color = Treatment)) +
  geom_point() +
  facet_grid(Transfer~.) +
  theme_bw()
  
```











