---
title: "DNA quantification using PicoGreen"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    number_sections: no
linkcolor: red
fontsize: 12pt
urlcolor: blue
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  cache = TRUE, 
  echo = FALSE,
	fig.align = "center",
	fig.height = 4,
	fig.width = 6)
library(tidyverse)
library(data.table)
library(invnet)
library(cowplot)
root <- rprojroot::is_r_package # Package root
source(root$find_file("misc/utils.R"))
source(root$find_file("misc/network_functions.R"))
write_all_csv <- T
write_all_pdf <- T

# 
communities <- fread(root$find_file("data/temp/communities.csv"))
communities_name <- communities$Community
communities_size <- communities$CommunitySize
isolates_ID_match <- fread(root$find_file("data/temp/isolates_ID_match.csv"))
isolates <- fread(root$find_file("data/output/isolates.csv"))
jean_isolates_RDP <- fread(root$find_file("data/temp/jean_isolates_RDP.csv"))
isolates_assembly <- fread(root$find_file("data/temp/isolates_assembly.csv"))
```


# DNA quantification using PicoGreen kit

Please see the protocol `output/protocol/DNAQuantification.pdf` from Maria for DNA quantiication using PicoGreen.


```{r}
# Read random network PicoGreen readout
random_network_C_P2 <- fread(root$find_file("data/raw/picogreen/random_network_C_P2.csv")) %>% 
  select(Well, `485/20,528/20`) %>% 
  set_names(c("Well", "OD"))


# Linear model of flurescence OD to DNA concentration
model <- random_network_C_P2 %>%
  filter(Well %in% paste0("H", 1:6)) %>%
  mutate(Concentration = c(1, .1, .05, .02, .01, 0)) %>%
  lm(data = ., formula = Concentration ~ OD)

# Predictitve DNA concnetration, unit is ug/mL
random_network_C_P2 %>%
  mutate(Concentrattion = predict(object = model, random_network_C_P2)) %>% 
  # Remove standard curve
  filter(!grepl("H", Well))
```


```{r}
random_network_C_P2 %>%
  filter(Well %in% paste0("H", 1:6)) %>%
  mutate(Concentration = c(1, .1, .05, .02, .01, 0)) %>%
  ggplot(aes(x = OD, y = Concentration)) +
  geom_point() + 
  geom_smooth(method = "lm") +
  theme_bw() +
  ggtitle("Standard curve for PicoGreen")
```

