---
title: "DNA extraction protocol (QIAGEN DNeasy96)"
author: "Chang-Yu Chang"
date: "`r Sys.Date()`" 
output: 
    pdf_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(data.table)
```

## Aims
Extract DNA from pellets in 96-well plates. 
`r n_plate = 1`

## Materials 
  - PBS `r 0.18 * 100 * 2` mL
  - proteinase K `r 0.025 * n_plate * 100` mL
  - buffer AL `r 0.2 * n_plate * 100` mL
  - ethanol `r 0.2 * n_plate * 100` mL
  - buffer AW1 `r 0.5 * n_plate * 100` mL 
  - buffer AW2 `r 0.5 * n_plate * 100` mL
  - buffer AE `r 0.1 * n_plate * 100` mL
  - DNeasy96 plate `r n_plate`
  - S-block or DW96 `r n_plate`
  - PCR plate `r n_plate`

## Procedures

  - [ ] Thaw pellet plates at room temperature.
  - [ ] Dissolve pellets in $180 \mu L$ of PBS.
  - [ ] Transfer the dissolved pellets to DNeasy microtube plates.
  - [ ] Add $25 \mu L$ proteinase K and $200 \mu L$ Buffer AL. 
  - [ ] Seal the plate with caps and mix by vortexing. Incubate at **56C** for **30 min**.
  - [ ] Add $200 \mu L$ pure ethanol.
  - [ ] Seal the plate with caps and mix thoroughly by vortexing. 
  - [ ] Assemble the DNeasy 96 plates on top of DW96s. Mark the DNeasy 96 plates.
  - [ ] Use mP1000 set at $625 \mu L$ to transfer the lysate of each sample from DW96s to each well of DNeasy96 plates (maximum $900 \mu L$). 
  - [ ] Seal DNeasy96 with AirPore film. Use vacuum to collect the flow-through.
  - [ ] Add $500 \mu L$ of Buffer AW1 to each sample. 
  - [ ] Seal DNeasy96 with AirPore film. Use vacuum to collect the flow-through.
  - [ ] Add $500 \mu L$ of Buffer AW2 to each sample. 
  - [ ] Seal DNeasy96 with AirPore film. Use vacuum to collect the flow-through.
  - [ ] Label two PCR plates. Place DNeasy96s on these PCR plates.
  - [ ] Add $100 \mu L$ Buffer AE to each sample, and seal the DNeasy 96 plates with new AirPore Tape Sheets (provided). 
  - [ ] Incubate for 1 min at room temperature (15–25°C). Centrifuge for **2 min** at **6000 rpm**.
  - [ ] Cover the PCR plates with aluminum foil and save it in -20C freezer.





