#' Convert T0 OD frequencies into CFU frequencies
#' This script calculates the uncertainty in OD-converted CFU frequenceis into each component variable
#' This script has two steps, first calculating mean of measurement, second estimating the uncertainty

library(tidyverse)

# Uncertainty in T0 CFU frequencies ----
# Read isolates epsilon uncertainty. isolates_epsilon_uncertainty.csv is generated by `script/02B-pairs_OD_CFU-01-epsilon_uncertainty.R`
isolates_epsilon_uncertainty <- read_csv("~/Dropbox/lab/emergent-coexistence/data/temp/isolates_epsilon_uncertainty.csv", col_types = cols())

# Pairs pairs_competition.csv is generated by `script/02-pairs-02-colony_count.R`
pairs_competition <- read_csv("~/Dropbox/lab/emergent-coexistence/data/temp/pairs_competition.csv", col_types = cols()) %>%
  mutate(Isolate1 = ordered(Isolate1, 1:12), Isolate2 = ordered(Isolate2, 1:12)) %>%
  mutate(ColonyCount2 = ColonyCount - ColonyCount1)

# Match epsilon from isolates table to pairs table. Use invnet function. Match isolates' epsilon to pairs
match_isolates_pairs <- function (pairs_df, isolates_df, variable_name = "Epsilon") {
  if (!("Isolate" %in% names(isolates_df))) {
    stop("Isolate df does not have a column of Isolate")
  } else if (!("Isolate1" %in% names(pairs_df)) | !("Isolate1" %in% names(pairs_df))) {
    stop("Pair df does not have columns of Isolate1 and Isolate2")
  }

  # Congifurate isolate df
  temp <- isolates_df %>%
    mutate(Isolate1 = ordered(Isolate, levels = 1:12), Isolate2 = ordered(Isolate, levels = 1:12)) %>%
    data.table::as.data.table()
  temp[,paste0("Isolate", 1:2)] <- temp[,c("Isolate", "Isolate")]
  temp[,paste0(variable_name, 1:2)] <- temp[,rep(variable_name, 2), with = FALSE] # temp is a data.table object
  temp <- as_tibble(temp) %>% mutate(Isolate1 = ordered(Isolate1, levels = 1:12), Isolate2 = ordered(Isolate2, levels = 1:12))

  # Match isolate 1 and isolate 2 by join isolates df to pairs df
  pairs_df %>%
    mutate(Isolate1 = ordered(Isolate1, levels = 1:12), Isolate2 = ordered(Isolate2, levels = 1:12)) %>%
    left_join(temp[,c("Community", "Isolate1", paste0(variable_name, 1))], by = c("Community", "Isolate1")) %>%
    left_join(temp[,c("Community", "Isolate2", paste0(variable_name, 2))], by = c("Community", "Isolate2")) %>%
    invisible() %>%
    return()
}
pairs_epsilon <- pairs_competition %>%
  match_isolates_pairs(isolates_epsilon_uncertainty, variable_name = "Epsilon") %>%
  match_isolates_pairs(isolates_epsilon_uncertainty, variable_name = "ErrorEpsilon")

# Uncertainty in T0 OD-converted CFU frequencies
pairs_CFU_freq_uncertainty_T0 <- pairs_epsilon %>%
  # Initial OD frequencies
  mutate(
    Isolate1ODFreq = Isolate1Freq / 100,
    Isolate2ODFreq = Isolate2Freq / 100,
  ) %>%
  # Partial derivatives
  mutate(
    PartialEpsilon1 =  Isolate1ODFreq * Isolate2ODFreq * Epsilon2 / (Isolate1ODFreq * Epsilon1 + Isolate2ODFreq * Epsilon2)^2,
    PartialEpsilon2 = -Isolate1ODFreq * Isolate2ODFreq * Epsilon1 / (Isolate1ODFreq * Epsilon1 + Isolate2ODFreq * Epsilon2)^2
  ) %>%
  mutate(
    Isolate1CFUFreqT0 = Isolate1ODFreq * Epsilon1 / (Isolate1ODFreq * Epsilon1 + Isolate2ODFreq * Epsilon2),
    ErrorIsolate1CFUFreqT0 = sqrt((PartialEpsilon1 * ErrorEpsilon1)^2 + (PartialEpsilon2 * ErrorEpsilon2)^2)
  ) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Isolate1CFUFreqT0, ErrorIsolate1CFUFreqT0)


# Uncertainty in T8 CFU frequencies ----
pairs_CFU_freq_uncertainty_T8 <- pairs_epsilon %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, ColonyCount, ColonyCount1, ColonyCount2, Contamination) %>%
  # Veriable uncertainties
  mutate(
    ErrorColonyCount1 = sqrt(ColonyCount1),
    ErrorColonyCount2 = sqrt(ColonyCount2)
  ) %>%
  # Partial derivatives
  mutate(
    ParialColonyCount1 = ColonyCount2 / (ColonyCount1 + ColonyCount2)^2,
    ParialColonyCount2 = -ColonyCount1 / (ColonyCount1 + ColonyCount2)^2
  ) %>%
  mutate(
    Isolate1CFUFreqT8 = ColonyCount1 / (ColonyCount1+ColonyCount2),
    ErrorIsolate1CFUFreqT8 = sqrt((ParialColonyCount1*ErrorColonyCount1)^2 + (ParialColonyCount2*ErrorColonyCount2)^2)
  ) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Isolate1CFUFreqT8, ErrorIsolate1CFUFreqT8, Contamination)

# Merge T0 and T8 CFU frequencies ----
## Mean
pairs_CFU_freq_uncertainty_mean <- pairs_CFU_freq_uncertainty_T0 %>%
  left_join(pairs_CFU_freq_uncertainty_T8, by = c("Community", "Isolate1", "Isolate2", "Isolate1Freq", "Isolate2Freq")) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Isolate1CFUFreqT0, Isolate1CFUFreqT8, Contamination) %>%
  gather("Time", "Isolate1CFUFreq", 6:7)

## Uncertainty
pairs_CFU_freq_uncertainty_error <- pairs_CFU_freq_uncertainty_T0 %>%
  left_join(pairs_CFU_freq_uncertainty_T8, by = c("Community", "Isolate1", "Isolate2", "Isolate1Freq", "Isolate2Freq")) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, ErrorIsolate1CFUFreqT0, ErrorIsolate1CFUFreqT8) %>%
  gather("Time", "ErrorIsolate1CFUFreq", 6:7)
pairs_CFU_freq_uncertainty_error$Time <- gsub("Error", "", pairs_CFU_freq_uncertainty_error$Time)

## Merge
pairs_CFU_freq_uncertainty <-
  left_join(pairs_CFU_freq_uncertainty_mean, pairs_CFU_freq_uncertainty_error,
            by = c("Community", "Isolate1", "Isolate2", "Isolate1Freq", "Isolate2Freq", "Time")) %>%
  # Discrete variable for plotting convenience
  mutate(Isolate1Freq = factor(Isolate1Freq), Isolate2Freq = factor(Isolate2Freq))

### Remoove the variable name prefix
pairs_CFU_freq_uncertainty$Time <- gsub("Isolate1CFUFreq", "", pairs_CFU_freq_uncertainty$Time)

### Set the T0 data to contamination == FALSE; There are only three pair-freq at T8 having contamination
pairs_CFU_freq_uncertainty[pairs_CFU_freq_uncertainty$Time == "T0", "Contamination"] <- FALSE

# Add one variable `RawDataType` ----
# This variable specifies where the freq data is collected
pairs_CFU_freq_uncertainty <- pairs_CFU_freq_uncertainty %>%
    mutate(RawDataType = case_when(
        Time == "T0" & !is.na(Isolate1CFUFreq) ~ "ODtoCFU", # OD converted to CFU by using epsilon
        Time == "T8" & !is.na(Isolate1CFUFreq) ~ "CFU", # CFU counts
        Time == "T0" & is.na(Isolate1CFUFreq) ~ "OD" # OD at T0
    ))


## If one isolate in the pair does not have epsilon value, then use OD frequency at T0
temp_index <- which(pairs_CFU_freq_uncertainty$Time == "T0" & is.na(pairs_CFU_freq_uncertainty$Isolate1CFUFreq))
pairs_CFU_freq_uncertainty$Isolate1CFUFreq[temp_index] <- as.numeric(as.character(pairs_CFU_freq_uncertainty$Isolate1Freq[temp_index]))/100
pairs_CFU_freq_uncertainty <- as_tibble(pairs_CFU_freq_uncertainty) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Time, Isolate1CFUFreq, ErrorIsolate1CFUFreq, RawDataType, Contamination)

write_csv(pairs_CFU_freq_uncertainty, "~/Dropbox/lab/emergent-coexistence/data/temp/pairs_CFU_freq_uncertainty.csv")

