#' Convert T0 OD frequencies into CFU frequencies
#' This script calculates the uncertainty in OD-converted CFU frequenceis into each component variable
#' This script has two steps, first calculating mean of measurement, second estimating the uncertainty


# Uncertainty in T0 CFU frequencies ----
# Read isolates epsilon uncertainty. isolates_epsilon_uncertainty.csv is generated by `script/02B-pairs_OD_CFU-01-epsilon_uncertainty.R`
isolates_epsilon_uncertainty <- fread(here::here("data/temp/isolates_epsilon_uncertainty.csv"))

# Pairs pairs_competition.csv is generted by `script/02-pairs-02-colony_count.R`
pairs_competition <- fread(here::here("data/temp/pairs_competition.csv")) %>%
  mutate(Isolate1 = ordered(Isolate1, 1:12), Isolate2 = ordered(Isolate2, 1:12)) %>%
  mutate(ColonyCount2 = ColonyCount - ColonyCount1)

# Match epsilon from isolates table to pairs table. Use invnet function. Match isolates' epsilon to pairs
match_isolates_pairs <- function (pairs_df, isolates_df, variable_name = "Epsilon") {
  if (!("Isolate" %in% names(isolates_df))) {
    stop("Isolate df does not have a column of Isolate")
  } else if (!("Isolate1" %in% names(pairs_df)) | !("Isolate1" %in% names(pairs_df))) {
    stop("Pair df does not have columns of Isolate1 and Isolate2")
  }

  # Congifurate isolate df
  temp <- isolates_df %>%
    mutate(Isolate1 = ordered(Isolate, levels = 1:12), Isolate2 = ordered(Isolate, levels = 1:12)) %>%
    data.table::as.data.table()
  temp[,paste0("Isolate", 1:2)] <- temp[,c("Isolate", "Isolate")]
  temp[,paste0(variable_name, 1:2)] <- temp[,rep(variable_name, 2), with = FALSE] # temp is a data.table object
  temp <- as_tibble(temp) %>% mutate(Isolate1 = ordered(Isolate1, levels = 1:12), Isolate2 = ordered(Isolate2, levels = 1:12))

  # Match isolate 1 and isolate 2 by join isolates df to pairs df
  pairs_df %>%
    mutate(Isolate1 = ordered(Isolate1, levels = 1:12), Isolate2 = ordered(Isolate2, levels = 1:12)) %>%
    left_join(temp[,c("Community", "Isolate1", paste0(variable_name, 1))], by = c("Community", "Isolate1")) %>%
    left_join(temp[,c("Community", "Isolate2", paste0(variable_name, 2))], by = c("Community", "Isolate2")) %>%
    invisible() %>%
    return()
}
pairs_epsilon <- pairs_competition %>%
  match_isolates_pairs(isolates_epsilon_uncertainty, variable_name = "Epsilon") %>%
  match_isolates_pairs(isolates_epsilon_uncertainty, variable_name = "ErrorEpsilon")

# Uncertainty in T0 OD-converted CFU frequencies
pairs_CFU_freq_uncertainty_T0 <- pairs_epsilon %>%
  # Initial OD frequencies
  mutate(
    Isolate1ODFreq = Isolate1Freq / 100,
    Isolate2ODFreq = Isolate2Freq / 100,
  ) %>%
  # Partial derivatives
  mutate(
    PartialEpsilon1 =  Isolate1ODFreq * Isolate2ODFreq * Epsilon2 / (Isolate1ODFreq * Epsilon1 + Isolate2ODFreq * Epsilon2)^2,
    PartialEpsilon2 = -Isolate1ODFreq * Isolate2ODFreq * Epsilon1 / (Isolate1ODFreq * Epsilon1 + Isolate2ODFreq * Epsilon2)^2
  ) %>%
  mutate(
    Isolate1CFUFreqT0 = Isolate1ODFreq * Epsilon1 / (Isolate1ODFreq * Epsilon1 + Isolate2ODFreq * Epsilon2),
    ErrorIsolate1CFUFreqT0 = sqrt((PartialEpsilon1 * ErrorEpsilon1)^2 + (PartialEpsilon2 * ErrorEpsilon2)^2)
  ) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Isolate1CFUFreqT0, ErrorIsolate1CFUFreqT0)


# Uncertainty in T8 CFU frequencies ----
pairs_CFU_freq_uncertainty_T8 <- pairs_epsilon %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, ColonyCount, ColonyCount1, ColonyCount2, Contamination) %>%
  # Veriable uncertainties
  mutate(
    ErrorColonyCount1 = sqrt(ColonyCount1),
    ErrorColonyCount2 = sqrt(ColonyCount2)
  ) %>%
  # Partial derivatives
  mutate(
    ParialColonyCount1 = ColonyCount2 / (ColonyCount1 + ColonyCount2)^2,
    ParialColonyCount2 = -ColonyCount1 / (ColonyCount1 + ColonyCount2)^2
  ) %>%
  mutate(
    Isolate1CFUFreqT8 = ColonyCount1 / (ColonyCount1+ColonyCount2),
    ErrorIsolate1CFUFreqT8 = sqrt((ParialColonyCount1*ErrorColonyCount1)^2 + (ParialColonyCount2*ErrorColonyCount2)^2)
  ) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Isolate1CFUFreqT8, ErrorIsolate1CFUFreqT8, Contamination)

# Merge T0 and T8 CFU frequencies ----
## Mean
pairs_CFU_freq_uncertainty_mean <- pairs_CFU_freq_uncertainty_T0 %>%
  left_join(pairs_CFU_freq_uncertainty_T8, by = c("Community", "Isolate1", "Isolate2", "Isolate1Freq", "Isolate2Freq")) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Isolate1CFUFreqT0, Isolate1CFUFreqT8, Contamination) %>%
  gather("Time", "Isolate1CFUFreq", 6:7)

## Uncertainty
pairs_CFU_freq_uncertainty_error <- pairs_CFU_freq_uncertainty_T0 %>%
  left_join(pairs_CFU_freq_uncertainty_T8, by = c("Community", "Isolate1", "Isolate2", "Isolate1Freq", "Isolate2Freq")) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, ErrorIsolate1CFUFreqT0, ErrorIsolate1CFUFreqT8) %>%
  gather("Time", "ErrorIsolate1CFUFreq", 6:7)
pairs_CFU_freq_uncertainty_error$Time <- gsub("Error", "", pairs_CFU_freq_uncertainty_error$Time)

## Merge
pairs_CFU_freq_uncertainty <-
  left_join(pairs_CFU_freq_uncertainty_mean, pairs_CFU_freq_uncertainty_error,
            by = c("Community", "Isolate1", "Isolate2", "Isolate1Freq", "Isolate2Freq", "Time")) %>%
  # Discrete variable for plotting convenience
  mutate(Isolate1Freq = factor(Isolate1Freq), Isolate2Freq = factor(Isolate2Freq))

### Remoove the variable name prefix
pairs_CFU_freq_uncertainty$Time <- gsub("Isolate1CFUFreq", "", pairs_CFU_freq_uncertainty$Time)

### Set the T0 data to contamination == FALSE; There are only three pair-freq at T8 having contaminations
pairs_CFU_freq_uncertainty[pairs_CFU_freq_uncertainty$Time == "T0", "Contamination"] <- FALSE

# Add one variable `RawDataType` ----
# This variable specifies where the freq data is collected
pairs_CFU_freq_uncertainty <- as.data.table(pairs_CFU_freq_uncertainty)
pairs_CFU_freq_uncertainty[Time == "T0" & !is.na(Isolate1CFUFreq), c("RawDataType")] <- "ODtoCFU" # OD converted to CFU by using epsilon
pairs_CFU_freq_uncertainty[Time == "T8" & !is.na(Isolate1CFUFreq), c("RawDataType")] <- "CFU" # CFU counts
pairs_CFU_freq_uncertainty[Time == "T0" & is.na(Isolate1CFUFreq), c("RawDataType")] <- "OD" # OD at T0

## If one isolate in the pair does not have epsilon value, then use OD frequency at T0
temp_index <- which(pairs_CFU_freq_uncertainty$Time == "T0" & is.na(pairs_CFU_freq_uncertainty$Isolate1CFUFreq))
pairs_CFU_freq_uncertainty$Isolate1CFUFreq[temp_index] <- as.numeric(as.character(pairs_CFU_freq_uncertainty$Isolate1Freq[temp_index]))/100
pairs_CFU_freq_uncertainty <- as_tibble(pairs_CFU_freq_uncertainty) %>%
  select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, Time, Isolate1CFUFreq, ErrorIsolate1CFUFreq, RawDataType, Contamination)

fwrite(pairs_CFU_freq_uncertainty, file = here::here("data/temp/pairs_CFU_freq_uncertainty.csv"))


# old code----
if (FALSE) {



  # Apply the calculation to the real data
  # Uncertainty in cell frequency at T0 ----
  #The cellular frequency of isolate A at T0 has the following form:
  #$freq(A)=\frac{\frac{f_1CFU_A}{DF_A v_A}}{\frac{f_1CFU_A}{DF_A v_A} + \frac{f_2CFU_B}{DF_B v_B}}=\frac{1}{1+\frac{f_2 CFU_B DF_A v_A}{f_1 CFU_A DF_B v_B}}$, where the error in this frequency has the form $\delta freq(A)= \sqrt{(\frac{\partial freq(A)}{\partial CFU_A}\delta CFU_A)^2 + (\frac{\partial freq(A)}{\partial CFU_B}\delta CFU_B)^2 + (\frac{\partial freq(A)}{\partial DF_A}\delta DF_A)^2 + (\frac{\partial freq(A)}{\partial DF_B}\delta DF_B)^2 + (\frac{\partial freq(A)}{\partial v_A}\delta v_A)^2 + (\frac{\partial freq(A)}{\partial v_B}\delta v_B)^2}$


  # T0 cell frequency and errors


  temp <- colonies_T0_mono %>%
    select(Community, Isolate, ColonyCount, DilutionFactor) %>%
    arrange(Community) %>%
    right_join(isolates_OD_620, by = c("Community", "Isolate")) %>%
    mutate(OD = 0.1, V = 20, CFU = ColonyCount,
      ErrorOD = 0.001, ErrorV = 0.4) %>%
    # Uncertainty in dilution factor
    mutate(ErrorCFU = sqrt(CFU),
      n = DilutionFactor,  V1 = 10, V2 = 90, ErrorV1 = 0.4, ErrorV2 = 2,
      PartialV1 = -n*(V1+V2)^(n-1)*V2/(V1^(n+1)),
      PartialV2 = n*(V1+V2)^(n-1)/(V1^n),
      DF = ((V1+V2)/V1)^n,
      ErrorDF = sqrt((PartialV1*ErrorV1)^2 + (PartialV2*ErrorV2)^2)) %>%
    select(-n, -V1, -V2, -ErrorV1, -ErrorV2, -PartialV1, -PartialV2) %>%
    select(Community, Isolate, ColonyCount, ErrorCFU, DF, ErrorDF, V, ErrorV)
  temp <- mutate(temp, Isolate1 = Isolate, Isolate2 = Isolate) %>% select(-Isolate)

  # Pairs
  temp_pairs <- left_join(pairs_competition, select(temp, -Isolate2), by = c("Community", "Isolate1")) %>%
    left_join(select(temp, -Isolate1), by = c("Community", "Isolate2"))

  pairs_cell_T0 <-
    mutate(temp_pairs,
      a = (Isolate2Freq*ColonyCount.y*DF.x*V.x) / (Isolate1Freq*ColonyCount.x*DF.y*V.y),
      PartialCFU_A = 1/(1+a)^2 * a / ColonyCount.x,
      PartialCFU_B = -1/(1+a)^2 * a / ColonyCount.y,
      PartialDF_A = -1/(1+a)^2 * a / DF.x,
      PartialDF_B = 1/(1+a)^2 * a / DF.y,
      PartialV_A = -1/(1+a)^2 * a / V.x,
      PartialV_B = 1/(1+a)^2 * a / V.y,
      CellFreq1T0 = 1 / (1 + a),
      ErrorCellFreq1T0 = sqrt((PartialCFU_A*ErrorCFU.x)^2 + (PartialCFU_B*ErrorCFU.y)^2 +
          (PartialDF_A*ErrorDF.x)^2 + (PartialDF_B*ErrorDF.y)^2 +
          (PartialV_A*ErrorV.x)^2 + (PartialV_B*ErrorV.y)^2)
    ) %>%
    select(-starts_with("Partial"))






  # Uncertainty in cell frequency at T8 ----
  # The cell frequency at T8 from CFU is $freq(A)=\frac{CFU_A}{CFU_A+CFU_B}$. The error in this frequency has the following form $\delta freq(A)= \sqrt{(\frac{\partial freq(A)}{\partial CFU_A}\delta CFU_A)^2 + (\frac{\partial freq(A)}{\partial CFU_B}\delta CFU_B)^2}$

  pairs_cell_T8 <- temp_pairs %>%
    select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, ColonyCount, ColonyCount1, ColonyCount2) %>%
    mutate(ErrorCFU_A = sqrt(ColonyCount1), ErrorCFU_B = sqrt(ColonyCount2)) %>%
    mutate(PartialCFU_A = ColonyCount2/(ColonyCount1+ColonyCount2)^2,
      PartialCFU_B = -ColonyCount1/(ColonyCount1+ColonyCount2)^2,
      CellFreq1T8 = ColonyCount1 / (ColonyCount1+ColonyCount2),
      ErrorCellFreq1T8 = sqrt((PartialCFU_A*ErrorCFU_A)^2 + (PartialCFU_B*ErrorCFU_B)^2)) %>%
    select(-starts_with("Partial"))

  # Match T0 and T8
  pairs_cell <-
    left_join(pairs_cell_T0, pairs_cell_T8, by = c("Community", "Isolate1", "Isolate2", "Isolate1Freq", "Isolate2Freq")) %>%
    left_join(mutate(pairs, Isolate1 = factor(Isolate1), Isolate2 = factor(Isolate2))) %>%
    select(Community, Isolate1, Isolate2, Isolate1Freq, Isolate2Freq, ColonyCount, ColonyCount1, ColonyCount2,
      CellFreq1T0, CellFreq1T8, ErrorCellFreq1T0, ErrorCellFreq1T8)

  pairs_cell_gathered <- pairs_cell %>%
    gather("Time", "ErrorCellFreq1", 8:9) %>%
    gather("Time2", "CellFreq1", 6:7) %>%
    # Remove mismatched rows that match T0 mean to T8 error
    filter(sub("\\w+T", "", Time) == sub("\\w+T", "", Time2)) %>%
    mutate(Isolate1Freq = factor(Isolate1Freq), Isolate2Freq = factor(Isolate2Freq)) %>%
    mutate(Time = ifelse(Time == "ErrorCellFreq1T0", "T0", "T8")) %>%
    select(-Time2) %>%
    distinct()
}
